# Generated by Django 4.2.7 on 2023-11-05 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "Worker", "verbose_name_plural": "Workers"},
        ),
    ]
